apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
      - name: netflix-app
        image: genci001/netflix:latest
        ports:
        - containerPort: 80
        env:
        - name: TMDB_V3_API_KEY
          valueFrom:
            secretKeyRef:
              name: tmdb-secret       # Replace with your secret name
              key: api-key            # Replace with your secret's key
